#pragma once

// 卡牌数量设置
#define NUM_CARDS_IN_GROUP				10
#define NUM_CARD_BUTTONS					5
#define NUM_CARD_NEXT_CARD				1
#define NUM_CARD_USED_CARD				1

// 卡牌武器参数
#define PARAM_SPEED_FIGHTER_PLANE			0.001f
#define PARAM_SPEED_BOMBING_PLANE		0.0005f

enum cardType {
	NO_TYPE = 0,
	CARD_TYPE_FIGHTER_PLANE,
	CARD_TYPE_BOMBING_PLANE,
	CARD_TYPE_ANTI_AIRCRAFT_MISSILE,
	CARD_TYPE_EARLY_WARNING_PLANE,
	CARD_TYPE_FLAK,
	CARD_TYPE_JAMMING_PLANE,
	CARD_TYPE_RADAR,
	CARD_TYPE_8,
	CARD_TYPE_9,
	CARD_TYPE_10,
	CARD_TYPE_11,
	CARD_TYPE_END
};

enum cardStatusInGaming {
	CARD_STATUS_NEXT_CARD = 0,
	CARD_STATUS_OCCUPIED,
	CARD_STATUS_FREE
};

enum BtnCardNo {
	BTN_CARD_NONE = -1,
	BTN_CARD_1,
	BTN_CARD_2,
	BTN_CARD_3,
	BTN_CARD_4,
	BTN_CARD_5
};