#pragma once

// 二人死斗 战场方格幅度
#define SQUARE_WIDTH_DOUBLE_BATTLE								54

// 物理引擎控制掩码
// 战争迷雾
#define BIT_MASK_CATEGORY_FROG_OF_WAR						0x0010
#define BIT_MASK_COLLISION_FROG_OF_WAR						0x0000
#define BIT_MASK_CONTACT_TEST_FROG_OF_WAR				0x0001
// 战斗机
#define BIT_MASK_CATEGORY_FIGHTER_PLANE						0x0001
#define BIT_MASK_COLLISION_FIGHTER_PLANE						0x0001
#define BIT_MASK_CONTACT_TEST_FIGHTER_PLANE			0x0010
// 轰炸机
#define BIT_MASK_CATEGORY_BOMBING_PLANE					0x0001
#define BIT_MASK_COLLISION_BOMBING_PLANE					0x0001
#define BIT_MASK_CONTACT_TEST_BOMBING_PLANE			0x0010
