#pragma once

// 默认游戏对战时长
#define DEFAULT_GAME_TIME												30000

// 战场方格大小
#define BATTLE_FIELD_SQUARE_WIDTH							108.0f

// 战场方格幅度
#define BATTLE_FIELD_WIDTH_IN_SQUARE							10
#define BATTLE_FIELD_HEIGHT_IN_SQUARE							13

// 物理引擎控制掩码
// 战争迷雾
#define BIT_MASK_CATEGORY_FROG_OF_WAR						0x0010
#define BIT_MASK_COLLISION_FROG_OF_WAR						0x0000
#define BIT_MASK_CONTACT_TEST_FROG_OF_WAR				0x0001
// 战斗机
#define BIT_MASK_CATEGORY_FIGHTER_PLANE						0x0001
#define BIT_MASK_COLLISION_FIGHTER_PLANE						0x0001
#define BIT_MASK_CONTACT_TEST_FIGHTER_PLANE			0x0010
// 轰炸机
#define BIT_MASK_CATEGORY_BOMBING_PLANE					0x0001
#define BIT_MASK_COLLISION_BOMBING_PLANE					0x0001
#define BIT_MASK_CONTACT_TEST_BOMBING_PLANE			0x0010


